### PR TITLE
UnencodedStatementVisitor resets value to previously

### LINKED ISSUE #468: HandlebarsDotNet.Handlebars.Configuration.NoEscape Applied Inconsistently
### Describe the bug
When iterating over an array using `#each`, the value of `Configuration.NoEscape` reverts to `false`.

### Expected behavior:
`Configuration.NoEscape` remains `true` when set to `true`.

### Test to reproduce
See PR [180](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/pull/180) in my repo.

### PR DESCRIPTION
**Pull request by tommysor**
existing value when done.

Fix #468 HandlebarsDotNet.Handlebars.Configuration.NoEscape Applied Inconsistently

Ref PR #473 [WIP] Configuration.NoEscape inconsistent fix

This PR does not deal with the question of general rules for encoding that was brought up in #473.

### CODE REVIEW

File: source/Handlebars/Compiler/Translation/Expression/UnencodedStatementVisitor.cs [hunk 1]
```diff
@@ -20,10 +20,14 @@ protected override Expression VisitStatementExpression(StatementExpression sex)
                 var writer = CompilationContext.Args.EncodedWriter;
                 var suppressEncoding = writer.Property(o => o.SuppressEncoding);
                 
+                var existingValue = new ExpressionContainer<bool>(Expression.Variable(typeof(bool)));
+                
                 return Block()
+                    .Parameter(existingValue)
```
Comment (zjklee) [inline source/Handlebars/Compiler/Translation/Expression/UnencodedStatementVisitor.cs:26]: Can be improved by introducing variable inline:
```suggestion
                return Block()
                    .Parameter<bool>(out var existingValue)
```

**Review by zjklee — APPROVED** [review]

**Comment by tonysneed** [comment]
Thank you @zjklee for merging this fix. Will you release the patch sometime soon? 😄

**Comment by zjklee** [comment]
@tonysneed , yes, I do plan to release a new version in a couple of days.
